import os
import re

# --- Configuration ---
RESEARCH_BRIEF_FILE = "data/research_brief.txt"
PODCAST_SCRIPT_FILE = "data/podcast_script.txt"

# --- File Operations ---
def read_research_brief(filepath: str) -> str | None:
    """Reads the content of the research brief file."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
        print(f"Successfully read research brief from: {filepath}")
        return content
    except FileNotFoundError:
        print(f"Error: Research brief file not found at {filepath}")
        return None
    except IOError as e:
        print(f"Error reading file {filepath}: {e}")
        return None

def save_podcast_script(script_content: str, filepath: str):
    """Saves the generated podcast script to a file."""
    try:
        # Ensure the data directory exists (it should from previous steps, but good practice)
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(script_content)
        print(f"Podcast script successfully saved to: {filepath}")
    except IOError as e:
        print(f"Error saving script to file {filepath}: {e}")

# --- LLM Script Generation (Placeholder) ---
def generate_podcast_script_from_brief(research_brief_text: str) -> str:
    """
    Generates a podcast script from the research brief using a placeholder LLM call.
    """
    print("\n--- LLM Podcast Script Generation ---")

    # Attempt to extract the topic from the first line of the brief for a slightly more dynamic dummy script
    topic = "the latest AI developments" # Default topic
    first_line_match = re.search(r"Research Brief for Topic: (.*)", research_brief_text)
    if first_line_match:
        extracted_topic = first_line_match.group(1).strip()
        if extracted_topic:
            topic = extracted_topic
    
    print(f"Topic for script generation (extracted or default): \"{topic}\"")

    prompt_for_llm = f"""
    You are a podcast scriptwriter. Based on the following research brief, please generate a short podcast script (approximately 3-5 paragraphs). 
    The script should be engaging and easy to understand for a general audience interested in AI.
    It should have the following structure:
    - INTRO: Briefly introduce the topic: "{topic}". Welcome listeners.
    - BODY: Explain the main points from the research brief in 1-3 paragraphs. Highlight key findings or developments.
    - OUTRO: Briefly conclude the segment and thank the listener.

    Research Brief:
    ---
    {research_brief_text}
    ---

    Please generate the podcast script now.
    """

    print("Prompt that would be sent to LLM:")
    # Print only a portion of the brief in the log if it's very long
    logged_brief_snippet = research_brief_text[:1000] + "..." if len(research_brief_text) > 1000 else research_brief_text
    logged_prompt = prompt_for_llm.replace(research_brief_text, logged_brief_snippet)
    print(logged_prompt)

    # --- Placeholder for actual LLM API call ---
    # Example using a hypothetical OpenAI-like client:
    #
    # from openai import OpenAI
    # client = OpenAI(api_key="YOUR_OPENAI_API_KEY") # Ensure API key is handled securely
    #
    # try:
    #     response = client.chat.completions.create(
    #         model="gpt-3.5-turbo", # Or "gpt-4" or other suitable model
    #         messages=[
    #             {"role": "system", "content": "You are a helpful podcast scriptwriter. You generate concise and engaging podcast scripts based on provided research material. Ensure the script has an INTRO, BODY, and OUTRO section."},
    #             {"role": "user", "content": prompt_for_llm} # Send the full prompt_for_llm
    #         ],
    #         temperature=0.7, # Adjust for creativity vs. factuality
    #         max_tokens=500  # Adjust based on desired script length
    #     )
    #     actual_script = response.choices[0].message.content
    #     print("Actual script would be generated by LLM.")
    #     # return actual_script 
    # except Exception as e:
    #     print(f"Error calling LLM API: {e}")
    #     # Fallback to dummy script or handle error appropriately
    # --- End of Placeholder ---

    dummy_script = f"""
[INTRO]
Welcome to today's AI News Summary! Today we're diving into some exciting updates on "{topic}". 
We've gathered some interesting research, so let's get right to it!

[BODY]
The latest research indicates some significant movements in this area. 
Based on multiple sources, it appears that [mention a generic positive development, e.g., "new capabilities are emerging rapidly"]. 
Furthermore, the information suggests that [another generic point, e.g., "there's a lot of buzz around potential release timelines and new features"]. 
It's clear that the field is evolving at a breakneck pace, keeping everyone on their toes.

[OUTRO]
And that's the gist of what we're seeing on "{topic}". 
It's definitely a space to watch! Thanks for tuning in to our AI News Summary. Stay curious!
"""
    print("Returning dummy podcast script.")
    return dummy_script.strip()

# --- Main Orchestration ---
def main():
    """
    Orchestrates reading the research brief, generating the podcast script,
    and saving it.
    """
    print("Starting podcast script generation process...")

    # 1. Read Research Brief
    research_brief = read_research_brief(RESEARCH_BRIEF_FILE)
    if research_brief is None:
        print("Halting script generation due to error reading research brief.")
        return

    # 2. Generate Podcast Script (using placeholder LLM function)
    podcast_script = generate_podcast_script_from_brief(research_brief)

    # 3. Save Podcast Script
    if podcast_script:
        save_podcast_script(podcast_script, PODCAST_SCRIPT_FILE)
    else:
        print("No podcast script was generated. Nothing to save.")
    
    print("\nPodcast script generation process completed.")

if __name__ == "__main__":
    main()
